name: AYT_Attendence
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  cupertino_icons: ^0.1.3

  carousel_slider: ^2.0.0
  splashscreen: ^1.2.0
  webview_flutter: ^1.0.7
  device_calendar: ^0.1.1
  http: ^0.12.2
  html: ^0.13.3+3

  firebase_core: ^0.5.0
  firebase_messaging: ^7.0.3
  overlay_support: ^1.0.5

#  month_picker_dialog: ^0.1.0

  pull_to_refresh: ^1.6.3

  flutter_spinkit: ^3.1.0

  grouped_buttons: ^1.0.3
  permission_handler: ^4.0.0
  device_info: ^0.4.1+2
  progress_dialog: ^1.2.4
  table_calendar: ^2.2.1
  shared_preferences: ^0.5.4+5
  flutter_datetime_picker: ^1.5.0
  firebase_auth: ^0.18.0+1
  google_sign_in: ^4.5.3
  cloud_firestore:  ^0.14.0+2
  firebase_storage: ^4.0.0
  random_string: ^2.0.1
#  intl: 0.16.0
  intl: any
  flutter_local_notifications: ^4.0.1+1
  barcode_scan: ^1.0.0
  bubbled_navigation_bar: ^0.0.3
  geolocator: ^5.1.3
  fluttertoast: ^7.1.8
  dio: ^3.0.10
  image_picker: ^0.6.6+5
  expansion_card: ^0.1.0
  curved_navigation_bar: ^0.3.0
  path_provider: ^0.4.0
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.


dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  assets:
    - assets/logo.png
    - assets/loading.flr
    - assets/ayt.png
    - assets/check_in.png
    - assets/check_out.png
    - assets/

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  fonts:
    - family: Raleway
      fonts:
        - asset: fonts/RockfordSans-Light.otf

          style: italic
#    - family: RobotoMono
#      fonts:
#        - asset: fonts/RobotoMono-Regular.ttf
#        - asset: fonts/RobotoMono-Bold.ttf
#          weight: 700
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
